name: build-frontend

on:
  push:

defaults:
 run:
  working-directory: frontend

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set api url
        run: |
          typesDir="./src/lib"
          typesFile="types.ts"
          apiUrl="https://kr.filipton.space/api"

          cp "$typesDir/$typesFile" "$typesDir/$typesFile.old"
          echo "export const apiUrl = \"$apiUrl\";" > "$typesDir/$typesFile"
          cat "$typesDir/$typesFile.old" | tail -n+2 >> "$typesDir/$typesFile"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store
      - name: Install dependencies & build
        run: pnpm install && pnpm build
      - name: "Docker build image"
        run: docker buildx build --platform linux/aarch64 --tag filipton/keyracer-client:latest --push -f .Dockerfile .

